from cycler import cycler
style= {
  "lines.linewidth": 2.0,
  "patch.linewidth": 0.5,
  "legend.fancybox": True,
  "axes.prop_cycle": cycler('color',[
    "#30a2da",
    "#fc4f30",
    "#e5ae38",
    "#6d904f",
    "#8b8b8b",
    "#006FA6", 
    "#A30059",
    "#af8dc3","#922329",
    "#1E6E00"
  ]),
  "axes.facecolor": "#ffffff",
  "axes.labelsize": "large",
  "axes.axisbelow": True,
  "axes.grid": True,
  "patch.edgecolor":  "#ffffff",
  "axes.titlesize": "x-large",
  "examples.directory": "",
  "figure.facecolor":  "#ffffff",
  "grid.linestyle": "-",
  "grid.linewidth": 1.0,
  "grid.color": "#c6b4b4",
  "axes.edgecolor": "#ffffff",
  "xtick.major.size": 0,
  "xtick.minor.size": 0,
  "ytick.major.size": 0,
  "ytick.minor.size": 0,
  "axes.linewidth": 3.0,
  "font.size":10.0,
  "font.family":"computer modern typewriter",
  "lines.linewidth": 4,
  "lines.solid_capstyle": "butt",
  "savefig.edgecolor":  "#ffffff",
  "savefig.facecolor":  "#ffffff",
  "figure.subplot.left"    : 0.09,
  "figure.subplot.right"   : 0.95, 
  "figure.subplot.bottom"  : 0.09,
  "text.usetex"         : True 
}